### ISSUE TITLE
3.3.4 RejectedExecutionException

### ISSUE THREAD

**Issue by brittmullen** [AdColony/AdColony-Android-SDK-3#37]
Fatal Exception: java.util.concurrent.RejectedExecutionException: Task java.util.concurrent.FutureTask@42625798 rejected from java.util.concurrent.ThreadPoolExecutor@42acb968[Terminated, pool size = 0, active threads = 0, queued tasks = 0, completed tasks = 17]
       at java.util.concurrent.ThreadPoolExecutor$AbortPolicy.rejectedExecution(ThreadPoolExecutor.java:2011)
       at java.util.concurrent.ThreadPoolExecutor.reject(ThreadPoolExecutor.java:793)
       at java.util.concurrent.ThreadPoolExecutor.execute(ThreadPoolExecutor.java:1334)
       at java.util.concurrent.AbstractExecutorService.submit(AbstractExecutorService.java:81)
       at java.util.concurrent.Executors$DelegatedExecutorService.submit(Executors.java:593)
       at com.adcolony.sdk.ac.a(SourceFile:66)
       at com.adcolony.sdk.ac.a(SourceFile:60)
       at com.adcolony.sdk.aa.a(SourceFile:22)
       at com.adcolony.sdk.aa.a(SourceFile:3)
       at com.adcolony.sdk.aa$a.a(SourceFile:71)
       at com.adcolony.sdk.p.run(SourceFile:111)
       at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1112)
       at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:587)
       at java.lang.Thread.run(Thread.java:841)

**Comment by brittmullen** [comment]
Fixed in 3.3.5
